export const LOADING ="LOADING"
export const GET_TRENDING ="GET_TRENDING"
export const GET_SEARCH ="GET_SEARCH"
export const ADD_TO_LIKED ="ADD_TO_LIKED"
export const GET_FAVORITES ="GET_FAVORITES"
